Add LFILTER and MFILTER
senx/warp10-platform pull request #1010
Opened 2021-08-19 13:57 UTC by ftence

Introduces two new functions `LFILTER` and `MFILTER` with a lot of similarities with `LMAP` and `MMAP`. Instead of mapping the element, those functions filter the element according to a boolean-returning macro.

Like `LMAP` and `MMAP`, is is possible to push the index of the element or not. It is pushed by default.

While this logic is achievable through a macro, those functions execute in 2/3 of the time of the macro version.

2021-08-19 15:54 UTC, randomboolean commented
How does it compare with the following line ?
`[ $list <% @some-filter-condition  <% DROP %> IFT %>   FOREACH ]`

2021-08-20 07:18 UTC, ftence commented
While this is a nice python-like list comprehension, this should be avoided because it can easily fail due to the stack depth limit.

The LFILTER function was compared to
```
[] SWAP
<% 
  DUP 2 % 0 ==
  <% +! %>
  <% DROP %>
  IFTE
%>
FOREACH
```

2021-08-23 14:10 UTC, hbs requested changes

2021-08-23 14:10 UTC, hbs commented on warp10/src/main/java/io/warp10/script/functions/LFILTER.java
> +      throw new WarpScriptException(getName() + " expects a macro on top of the stack.");
Avoid referring to the stack in error messages.

2021-08-23 14:10 UTC, hbs commented on warp10/src/main/java/io/warp10/script/functions/LFILTER.java
> +      throw new WarpScriptException(getName() + " expects a list below the macro on top of the stack.");
Ditto ... "operates on a LIST"

2021-08-23 14:10 UTC, hbs commented on warp10/src/main/java/io/warp10/script/functions/MFILTER.java
> +      throw new WarpScriptException(getName() + " expects a macro on top of the stack.");
Ditto above

2021-08-23 14:10 UTC, hbs commented on warp10/src/main/java/io/warp10/script/functions/MFILTER.java
> +        throw new WarpScriptException(getName() + " expect the filter macro to return a BOOLEAN for each element.");
expects

2021-08-23 14:10 UTC, hbs commented on warp10/src/main/java/io/warp10/script/functions/LFILTER.java
> +        throw new WarpScriptException(getName() + " expect the filter macro to return a BOOLEAN for each element.");
expects

2021-08-23 14:10 UTC, hbs commented on warp10/src/main/java/io/warp10/script/functions/LFILTER.java
> +    ArrayList<Object> result = new ArrayList<Object>(n);
Allocating n elements may be inefficient because we do not know ahead of time the proportion of elements which will be retained.

2021-08-23 14:10 UTC, hbs commented on warp10/src/main/java/io/warp10/script/functions/MFILTER.java
> +    LinkedHashMap<Object, Object> result = new LinkedHashMap<Object, Object>(map.size());
Allocating an identical number of elements may be inefficient because we do not know ahead of time the proportion of elements which will be retained.

2021-08-24 15:18 UTC, hbs approved these changes

2021-08-24 15:19 UTC, merged