Output format.attr
senx/warp10-platform pull request #1055
Opened 2021-12-27 19:28 UTC by hbs

2022-01-24 10:17 UTC, steven-gueguen requested changes

2022-01-24 10:17 UTC, steven-gueguen commented on warp10/src/main/java/io/warp10/hadoop/Warp10RecordWriter.java
>        count++;
'count' is unused

2022-01-24 10:17 UTC, steven-gueguen commented on warp10/src/main/java/io/warp10/hadoop/Warp10RecordWriter.java
>    private boolean init = false;
init should be volatile to avoid double-checked locking

2022-01-24 10:17 UTC, steven-gueguen commented on warp10/src/main/java/io/warp10/hadoop/Warp10RecordWriter.java
>      long count = 0L;
'count' is unused

2022-01-26 16:56 UTC, hbs commented
PTAL

2022-01-26 17:11 UTC, steven-gueguen approved these changes

2022-01-26 17:12 UTC, merged