Added capability support
senx/warp10-platform pull request #1106
Opened 2022-07-11 14:38 UTC by hbs

2022-07-13 10:01 UTC, pi-r-p requested changes
In the case a script do several REXEC on different endpoints, you need to reload capability between each rexec, and it is hard to keep track of the endpoint URL (you cannot read it anymore in the code).

Why not just read patterns from the capability, building a WebAccessController from this, and keep the explicit endpoint in the signature ? (so, keep the same signature)

`rexec` capability will just override warpscript.rexec.endpoint.patterns configuration, and this will be consistent with other capabilities.

2022-07-18 16:11 UTC, pi-r-p commented on warp10/src/main/java/io/warp10/script/ext/rexec/RexecWarpScriptExtension.java
> +  private static String CONF_CAPABILITY = "warpscript.rexec.capability";
As capabilities are not well known yet, the template may also explicit what it is:
```
# enforce the use of CAPADD with a token that contains the authorized patterns. Generate a read or write token that contains attributes { '.cap:rexec' '.*warp.*' }
# the token capability will override warpscript.rexec.endpoint.patterns
```

2022-08-08 06:22 UTC, hbs commented on warp10/src/main/java/io/warp10/script/ext/rexec/REXEC.java
> +
Enabling capabilities means that you CAN use capabilities, not that they become mandatory, therefore it seems natural to revert to the configured default patterns as configured.

2022-08-08 06:27 UTC, hbs commented
PTAL

2022-08-16 08:42 UTC, pi-r-p approved these changes

2022-08-17 13:20 UTC, merged