Variables
senx/warp10-platform pull request #1120
Opened 2022-09-09 15:46 UTC by randomboolean

Add LSTORE and MSTORE to more easily manipulate variables.

1/
The usual pattern:
`[ $o1 $o2 $o3 ]  LIST-> DROP [ "varname1" "varname2" "varname3" ] LSTORE`
is simplified into:
`[ $o1 $o2 $o3 ] [ "varname1" "varname2" "varname3" ] LSTORE`
which makes it a bit more readable and does not spill the list on the stack (bad practice for big lists).

2/
```
{ 'varname1' $o1
  'varname2' $o2
... }
MSTORE
```
is a convenient way to store objects into symbols. This also makes some warpscripts more readable since multiple `$map "varnameN" GET` are simplified into `$varnameN`.

3/ A commit had the side effect to sort the imports of WarpScriptLib.java and unfold import io.warp10.script.functions.* (due to my IDE automatic import settings)

2022-09-12 06:50 UTC, hbs requested changes

2022-09-12 06:50 UTC, hbs commented on warp10/src/main/java/io/warp10/script/functions/LSTORE.java
> +    if (variables.size() != objects.size()) {
We should support those size discrepancies. If the variable list is shorter simply store those variables, if the first list is shorter, assume NULL as the value for the other elements.

2022-09-12 06:50 UTC, hbs commented on warp10/src/main/java/io/warp10/script/functions/LSTORE.java
> +        stack.store(symbol.toString(), objects.get(i));
Use a cast to String, since you've checked that you only have Longs and Strings.

2022-09-12 06:50 UTC, hbs commented on warp10/src/main/java/io/warp10/script/functions/MSTORE.java
> +        stack.store(symbol.toString(), entry.getValue());
Use cast to String

2022-09-12 06:51 UTC, hbs commented
You should add LCSTORE and MCSTORE variants too.

2022-09-12 09:28 UTC, hbs requested changes

2022-09-12 09:28 UTC, hbs commented on warp10/src/main/java/io/warp10/script/functions/LCSTORE.java
> +//
Merce LCSTORE with LSTORE by adding a flag to its constructor, the code being almost identical.

2022-09-12 09:28 UTC, hbs commented on warp10/src/main/java/io/warp10/script/functions/MCSTORE.java
> +//
Merge MCSTORE with MSTORE with an added flag in constructor.

2022-09-14 08:29 UTC, hbs approved these changes

2022-09-14 08:29 UTC, merged

2022-09-14 10:47 UTC, pi-r-p commented
```
some-map MSTORE is a convenient way to store objects of a map into its keys. This makes some warpscripts more readable since multiple $map "varnameN" GET are simplified into $varnameN (which is also better for auto-completion).
```

Well, no, those created by MSTORE won't be available for auto completion at all.

(LSTORE can be added to VSCode parsing, no problem)

2022-09-14 10:57 UTC, randomboolean commented
Got it. Auto-completion would have just been a consequence of this feature anyway.

2022-09-14 11:17 UTC, hbs commented
Actually one point I overlooked in my review is the fact that ASREGS should be modified to fail if LSTORE/LCSTORE/MSTORE/MCSTORE are used.

2022-09-15 09:36 UTC, pi-r-p commented
`some-map MSTORE`  would lead to no autocompletion at all. But `some-map [ 'key1' 'key3' ] MSTORE` could be a good idea, to store only a few keys of the input, and to provide autocompletion.