Fixed capabilities handling in GUARD calls
senx/warp10-platform pull request #1151
Opened 2022-11-14 09:04 UTC by hbs

2022-11-21 13:49 UTC, steven-gueguen commented on warp10/src/main/java/io/warp10/script/functions/GUARD.java
> +        Capabilities.set(stack, capabilities);
If there is no capability set with before the call to GUARD, all capabilities in macro will leak.

2022-11-21 13:50 UTC, steven-gueguen commented on warp10/src/main/java/io/warp10/script/functions/GUARD.java
> +              capabilities.remove(cap);
If capabilities is null, the export will fail

2022-11-23 15:32 UTC, hbs commented
PTAL

2022-11-24 10:15 UTC, steven-gueguen approved these changes

2022-11-30 11:13 UTC, pi-r-p requested changes
There is one weird edge case: CAPEXPORT also export cap deletion when the guarded macro does not fail. 

```
<%
  SAVE '.context' STORE
  // token with 'runner.reschedule.min.period' 2000 and "http.size": "100000000"  
  CAPADD // will  leak outside the macro, with 'runner.reschedule.min.period' 2000
  <%
    'runner.reschedule.min.period' CAPDEL // erase the previous one (2000)
    // token with 'runner.reschedule.min.period' 10
    
    CAPADD 
    'runner.reschedule.min.period' CAPGET  "10" == 'not 10 here ?' ASSERTMSG
    'runner.reschedule.min.period' CAPDEL // erase it
    //'runner.reschedule.min.period' CAPGET ISNULL 'is not erased here ?' ASSERTMSG

    // should not export "runner.reschedule.min.period": null, but does so...
    [ 'runner.reschedule.min.period' '' 'toto' ] CAPEXPORT

    //FAIL 
    DROP
    'result of the macro'
  %> 
  $.context -1 GUARD

%>
'macro' STORE

[ 'runner.reschedule.min.period' 'http.size' 'toto' ] CAPGET 
// "runner.reschedule.min.period": "2000"  if the macro fails
// "runner.reschedule.min.period": null if the macro does not fail
```

2022-11-30 11:19 UTC, hbs commented
The GUARD call restores the capabilities to their value pre-call, except for those which were altered during the call and which were explicitely exported.

Isn't that excactly what you observed?

2022-12-15 07:17 UTC, merged