Added support for default token attributes
senx/warp10-platform pull request #1153
Opened 2022-11-16 08:47 UTC by hbs

2022-11-21 17:25 UTC, steven-gueguen requested changes

2022-11-21 17:25 UTC, steven-gueguen commented on warp10/src/main/java/io/warp10/continuum/Tokens.java
> +        attributes = new LinkedHashMap<String,String>(defaults);
Defaults attributes wont' be propagated

2022-11-23 15:33 UTC, hbs commented
PTAL

2022-11-30 14:11 UTC, pi-r-p requested changes

2022-11-30 14:11 UTC, pi-r-p commented on etc/conf.templates/distributed/00-warp.conf.template
> +
Not the best example, .nodelete leads to a non delete instance.

2022-12-22 07:40 UTC, hbs commented
PTAL

2022-12-23 14:18 UTC, steven-gueguen approved these changes

2022-12-23 14:38 UTC, merged