Added config for default capabilities
senx/warp10-platform pull request #1163
Opened 2022-11-23 16:12 UTC by hbs

2022-12-09 15:07 UTC, steven-gueguen requested changes

2022-12-09 15:07 UTC, steven-gueguen commented on warp10/src/main/java/io/warp10/warp/sdk/Capabilities.java
>      if (stack.getAttribute(WarpScriptStack.CAPABILITIES_ATTR) instanceof Capabilities) {
Default capabilities should be added here also

2022-12-23 14:46 UTC, steven-gueguen requested changes

2022-12-23 14:46 UTC, steven-gueguen commented on warp10/src/main/java/io/warp10/warp/sdk/Capabilities.java
> +      return DEFAULT_CAPABILITIES.get(name);
If they are some capabilities defined, the default one cannot be accessed.

2022-12-23 14:58 UTC, hbs commented
PTAL

2022-12-23 15:21 UTC, steven-gueguen approved these changes

2023-01-02 08:50 UTC, merged