Fixed TokenGen so there is no risk of overwriting the input file when…
senx/warp10-platform pull request #1176
Opened 2023-01-02 10:26 UTC by hbs

… no output was specified.

2023-01-03 15:45 UTC, steven-gueguen requested changes

2023-01-03 15:45 UTC, steven-gueguen commented on warp10/src/main/java/io/warp10/TokenGen.java
> +      System.err.println("Usage: TokenGen config ... in");
Should be `Arrays.copyOf(args, args.length - 1))` line 54

2023-01-04 21:06 UTC, hbs commented
PTAL

2023-01-11 10:11 UTC, steven-gueguen approved these changes

2023-01-11 10:13 UTC, merged