Output ticks in MAP
senx/warp10-platform pull request #1177
Opened 2023-01-06 17:03 UTC by randomboolean

- Enable passing output ticks parameter when using the input list syntax of MAP instead of occurrences parameters
- Fix #953 : the current output tick is no longer counted in parameter pre (or post) if it matches a tick of the input series

2023-01-17 10:46 UTC, steven-gueguen requested changes
Please also update the corresponding tests.

2023-01-17 11:01 UTC, randomboolean commented on warp10/src/main/java/io/warp10/continuum/gts/GTSHelper.java
> +              // if the current output tick matches an input tick then there will be one tick more in the sliding window
Maybe we can allow output tick to be also reverse sorted if the input syntax is a list or if the the input syntax is a map and occurrences is 0.

2023-01-17 15:11 UTC, steven-gueguen requested changes

2023-01-17 15:11 UTC, steven-gueguen commented on warp10/src/main/java/io/warp10/script/functions/MAP.java
> +            descending = elt <= lastElt;
Should it be `descending = elt < lastElt;` instead?

2023-01-17 15:11 UTC, steven-gueguen commented on warp10/src/main/java/io/warp10/script/functions/MAP.java
> +            ascending = elt >= lastElt;
Should it be `ascending = elt > lastElt;` instead?

2023-01-27 12:54 UTC, steven-gueguen requested changes
Please correct the unit test accordingly.

2023-02-06 15:26 UTC, pi-r-p requested changes
To discuss: 
- We must fail instead of doing unexpected things
Ready for your review:
- tests on 3.x branch in documentation (compile with revision 3.0.0).

2023-02-12 22:16 UTC, pi-r-p requested changes

2023-02-12 22:16 UTC, pi-r-p commented on warp10/src/main/java/io/warp10/script/functions/MAP.java
> +    }
Can you add something like "parameter name and behavior are changed, read the doc"
It is not a simple "replace".

2023-03-01 12:55 UTC, pi-r-p approved these changes

2023-03-01 16:52 UTC, steven-gueguen approved these changes

2023-03-01 17:07 UTC, merged