Minor changes to backend
senx/warp10-platform pull request #1192
Opened 2023-02-01 14:38 UTC by hbs

2023-02-16 11:43 UTC, Giwi requested changes

2023-02-16 11:43 UTC, Giwi commented on warp10/src/main/java/io/warp10/continuum/store/Store.java
> +    if ("true".equals(properties.getProperty(Configuration.STORE_SKIP_WRITE))) {
Could be replaced by
`this.SKIP_WRITE = "true".equals(properties.getProperty(Configuration.STORE_SKIP_WRITE));`

2023-02-16 11:43 UTC, Giwi commented on warp10/src/main/java/io/warp10/continuum/store/Store.java
>        long count = 0L;
updated L930 but never used, could be deleted

2023-02-16 11:43 UTC, Giwi commented on warp10/src/main/java/io/warp10/fdb/FDBClear.java
> +  public FDBClear(byte[] key) {
Never used

2023-02-16 11:43 UTC, Giwi commented on warp10/src/main/java/io/warp10/fdb/FDBKVScanner.java
> +  public FDBKVScanner(FDBContext fdbContext, Database db, FDBScan scan, StreamingMode mode) {
Never used

2023-02-16 11:43 UTC, Giwi commented on warp10/src/main/java/io/warp10/fdb/FDBMutation.java
> +  public void apply(Transaction txn);
Modifier 'public' is redundant for interface members

2023-02-16 11:43 UTC, Giwi commented on warp10/src/main/java/io/warp10/fdb/FDBPool.java
> + * Experimenting is key as sizing depends n the type of load of each deployment.
Typo "depends on"

2023-02-16 11:43 UTC, Giwi commented on warp10/src/main/java/io/warp10/fdb/FDBSet.java
> +  public FDBSet(byte[] key, byte[] value) {
Never used

2023-02-16 11:43 UTC, Giwi commented on warp10/src/main/java/io/warp10/fdb/FDBStoreClient.java
> +    // Sort metadatas so as to optimize the range scans
Typo: "Sort metadatas to optimize the range scans"

2023-02-16 11:43 UTC, Giwi commented on warp10/src/main/java/io/warp10/fdb/FDBUtils.java
> +    if (size >= 4500000) {
Could be replaced by: ` return size >= 4500000;`

2023-02-16 11:43 UTC, Giwi commented on warp10/src/main/java/io/warp10/hadoop/WritableUtils.java
>      if ("true".equals(WarpConfig.getProperty(Configuration.CONFIG_WARPSCRIPT_HADOOP_STRICTWRITABLES))) {
Could be replaced by: `strictWritables = "true".equals(WarpConfig.getProperty(Configuration.CONFIG_WARPSCRIPT_HADOOP_STRICTWRITABLES));`

2023-02-16 11:43 UTC, Giwi commented on warp10/src/main/java/io/warp10/hadoop/WritableUtils.java
>      if ("true".equals(WarpConfig.getProperty(Configuration.CONFIG_WARPSCRIPT_HADOOP_RAWWRITABLES))) {
Could be replaced by: `
    rawWritables = "true".equals(WarpConfig.getProperty(Configuration.CONFIG_WARPSCRIPT_HADOOP_RAWWRITABLES));`

2023-02-16 11:43 UTC, Giwi commented on warp10/src/main/java/io/warp10/script/ScriptRunnerConsumerFactory.java
> +import java.time.Duration;
Unused imports

2023-02-17 13:24 UTC, hbs commented on crypto/src/main/java/io/warp10/crypto/DummyKeyStore.java
> +    setKey(KeyStore.AES_FDB_METADATA, new byte[32]);
That could be a change we do later, but for now _FDB_ are to be considere related to the storage backend, vs _KAFKA_

2023-02-17 13:24 UTC, hbs commented on crypto/src/main/java/io/warp10/crypto/KeyStore.java
> +  public static final String AES_FDB_METADATA = "warp.aes.fdb.metadata";
ditto

2023-02-17 13:38 UTC, hbs commented on warp10/src/main/java/io/warp10/continuum/KafkaWebCallService.java
> +import java.util.concurrent.Future;
removed in future PR

2023-02-22 08:25 UTC, pi-r-p approved these changes

2023-02-27 07:36 UTC, hbs commented on warp10/src/main/java/io/warp10/script/ScriptRunnerConsumerFactory.java
> +import java.time.Duration;
Leaving it for future use.

2023-03-01 13:51 UTC, merged