remove remaining references to removed function of 3.x
senx/warp10-platform pull request #1193
Opened 2023-02-01 17:50 UTC by pi-r-p

Search and delete references to removed functions:
- AUTHENTICATE
- CHUNKENCODER
- CUDF
- DOC
- DOCMODE
- FROMBITS
- ISAUTHENTICATED
- MACROCONFIGSECRET
- TOBITS
- UDF
- STACKPSSECRET
- TOKENSECRET
- MAXURLFETCHCOUNT
- MAXURLFETCHSIZE
- URLFETCH

Remove unmaintained test tool to export list of functions (better use `FUNCTIONS` for inventory).

2023-02-03 16:22 UTC, steven-gueguen requested changes

2023-02-03 16:22 UTC, steven-gueguen commented on etc/conf.templates/distributed/70--extensions.conf.template
> +// TOKENDUMP, TOKENGEN
Please update the copyright date

2023-02-03 16:22 UTC, steven-gueguen commented on warp10/src/main/java/io/warp10/continuum/store/Constants.java
>    public static final String TOKEN_ATTR_NOFETCH = ".nofetch";
Please update the copyright date

2023-02-03 16:22 UTC, steven-gueguen commented on warpscript/build.gradle
>              include 'io/warp10/CapacityExtractorOutputStream.*'
Please update the copyright date

2023-02-05 22:29 UTC, pi-r-p commented
Done

2023-02-07 10:51 UTC, steven-gueguen approved these changes

2023-02-09 09:11 UTC, merged