Removed Thrift directory service
senx/warp10-platform pull request #1202
Opened 2023-02-28 14:43 UTC by hbs

2023-03-01 13:14 UTC, pi-r-p approved these changes

2023-03-03 15:24 UTC, steven-gueguen approved these changes

2023-03-03 15:48 UTC, hbs commented
PTAL post conflict resolution

2023-03-03 16:05 UTC, steven-gueguen requested changes

2023-03-03 16:05 UTC, steven-gueguen commented on warp10/src/main/java/io/warp10/continuum/DirectoryUtil.java
> +import io.warp10.continuum.sensision.SensisionConstants;
Unused imports

2023-03-03 16:11 UTC, steven-gueguen approved these changes

2023-03-03 16:18 UTC, merged