Added finer grain capabilities
senx/warp10-platform pull request #1205
Opened 2023-03-02 07:46 UTC by hbs

2023-03-08 10:49 UTC, pi-r-p requested changes
These functions are added to WarpScript in a static block of FDBStoreClient.

Why isn't it in WarpScriptLib, to be consistent with leveldb functions ? 

Usage: 
In a standalone (leveldb), I may want to REXEC something to a fdb one, and this will fail:
```
<% 
  $x FDBGET   //will fail here, not able to build the function
%> { 'x' $tenant } DEREF  $url REXEC
```

2023-03-08 10:51 UTC, hbs commented
The functions are only added when using FDB. If you want to do what you showed, use 'FDBGET' EVAL

2023-03-08 11:17 UTC, pi-r-p commented
I know the workaround, but it is not as convenient. 

Functions are defined as a standard or by an extension, not by the backend type. And you already check the backend in all these functions, so it won't be a problem to treat them as leveldb ones.

In the current documentation process, it will more easy not to add this kind of exceptions.

2023-03-08 11:58 UTC, hbs commented
Those functions were added in PR#1192 that you approved. We can modify the way they are defined but those types of concerns should be raised within the convo of the appropriate PR.

2023-03-09 10:20 UTC, pi-r-p requested changes
- `FDBSIZE` should have the same optional regexp whitelist as `FDBTENANT`.

Outside of this PR scope, but not spotted before :
- `FDBTENANT` returns an empty map when tenant does not exists. `FDBSIZE` raises an exception. It is not consistent.
- Is there a way to list all existing tenants ? (it could be very handy, and restricted to fdb.admin cap)

2023-03-23 17:30 UTC, pi-r-p requested changes

2023-03-23 17:30 UTC, pi-r-p commented on warp10/src/main/java/io/warp10/fdb/FDBSIZE.java
> +      throw new WarpScriptException(getName() + " missing '" + FDBUtils.CAPABILITY_SIZE + "' or '" + FDBUtils.CAPABILITY_ADMIN + "' capability.");
if you do not have CAPABILITY_ADMIN nor CAPABILITY_SIZE, you can read everything !

2023-03-23 17:30 UTC, pi-r-p commented on warp10/src/main/java/io/warp10/fdb/FDBTENANT.java
> +    } else {
Same wrong condition path, everything is allowed with no caps at all.

2023-03-23 18:11 UTC, hbs commented
PTAL

2023-03-24 08:48 UTC, pi-r-p approved these changes

2023-03-24 08:49 UTC, merged