Added forced sorting of GTS when gskip/gcount is specified.
senx/warp10-platform pull request #1246
Opened 2023-04-25 14:00 UTC by hbs

Ensure that GTS results from Directory requests are sorted when gskip/gcount are specified. This is of importance if there are several Directory instances.

2023-04-25 15:41 UTC, steven-gueguen requested changes
The StandaloneSplitsHandler class should also be modified

2023-04-25 19:44 UTC, hbs commented
> The StandaloneSplitsHandler class should also be modified

The standalone version of the Directory is accessed by a single thread and the results are always sorted, so this is not necessary per se. Will add it anyway in case we make the inner workings evolve so we won't have then bad surprises.

2023-04-25 19:47 UTC, hbs commented
PTAL

2023-04-26 15:39 UTC, steven-gueguen approved these changes

2023-04-26 18:29 UTC, merged