Filler.value
senx/warp10-platform pull request #1303
Opened 2023-08-31 15:18 UTC by randomboolean

2023-08-31 16:24 UTC, hbs requested changes

2023-08-31 16:24 UTC, hbs commented on warp10/src/main/java/io/warp10/script/filler/FillerValue.java
> +    this.value = value;
You should check here that value is a supported type (Long, Double, Boolean, String, byte array)

2023-08-31 16:24 UTC, hbs commented on warp10/src/main/java/io/warp10/script/filler/FillerValue.java
> +        }
You should check that the first three parameters are instances of Number otherwise you may trigger class cast exceptions further down the line.

2023-08-31 16:24 UTC, hbs commented on warp10/src/main/java/io/warp10/script/filler/FillerValue.java
> +public class FillerValue extends NamedWarpScriptFunction implements WarpScriptFillerFunction {
You need to explicitely define how an instance of FillerValue is SNAPSHOT

2023-09-05 08:43 UTC, steven-gueguen requested changes

2023-09-05 08:43 UTC, steven-gueguen commented on warp10/src/main/java/io/warp10/script/filler/FillerValue.java
> +        if (!(datapoint.get(2) instanceof Long)) {
Does not work when elevation is NaN

2023-09-05 09:27 UTC, steven-gueguen approved these changes

2023-09-05 09:28 UTC, hbs commented on warp10/src/main/java/io/warp10/script/filler/FillerValue.java
> +  public String toString() {
Better to implement Snapshotable and have toString call snapshot()

2023-09-05 09:29 UTC, hbs commented on warp10/src/main/java/io/warp10/script/filler/FillerValue.java
> +      sb.append(WarpScriptStack.COMMENT_END);
missing whitespace before closing comment

2023-09-05 09:38 UTC, hbs commented on warp10/src/main/java/io/warp10/script/filler/FillerValue.java
> +      sb.append(" Error while snapshoting function" + getName());
missing whitespace before function name

2023-09-07 07:53 UTC, hbs approved these changes

2023-09-07 07:57 UTC, steven-gueguen approved these changes

2023-09-07 08:06 UTC, merged