extend ROUND to lists and GTSs
senx/warp10-platform pull request #1305
Opened 2023-09-12 13:46 UTC by randomboolean

2023-09-12 15:27 UTC, steven-gueguen requested changes

2023-09-12 15:27 UTC, steven-gueguen commented on warp10/src/main/java/io/warp10/script/WarpScriptLib.java
> +    addNamedWarpScriptFunction(new NumericalUnaryFunction(ROUND, null, Math::round));
The `ROUND` function will now return a `DOUBLE` instead of a `LONG`

2023-09-15 08:51 UTC, steven-gueguen approved these changes

2023-09-18 08:06 UTC, pi-r-p requested changes
Is it possible to add a shortcut when the gts is already a LONG one ? (juste clone it)

2023-09-18 08:10 UTC, pi-r-p commented
(I didn't look at #1306 first, but it still applies)

2023-09-19 08:23 UTC, randomboolean commented
> Is it possible to add a shortcut when the gts is already a LONG one ? (juste clone it)

PTAL

2023-10-06 08:17 UTC, pi-r-p approved these changes

2023-10-07 09:16 UTC, merged