Optimize numerical functions
senx/warp10-platform pull request #1306
Opened 2023-09-13 13:40 UTC by randomboolean

depends on #PR1305

Refactor instanciation of GTS operators at static time.
Previously, they were instantiated for each GTS at execution time.

2023-09-18 09:34 UTC, pi-r-p requested changes
add a shortcut when double to long and already long, for public NumericalUnaryFunction(String name, DoubleToLongFunction opDL)  (this is only used for ROUND)

2023-09-19 08:38 UTC, randomboolean commented
> add a shortcut when double to long and already long, for public NumericalUnaryFunction(String name, DoubleToLongFunction opDL) (this is only used for ROUND)

PTAL

2023-09-22 08:24 UTC, pi-r-p requested changes
You cannot clone() at this level. For example ABS takes long and outputs long... It won't work with this approach. ROUND is the only long->long example where clone() can be used safely.

2023-09-22 08:43 UTC, randomboolean commented
> You cannot clone() at this level. For example ABS takes long and outputs long... It won't work with this approach. ROUND is the only long->long example where clone() can be used safely.

I cannot reproduce this bug.
This test `NEWGTS 1 10 <% NaN NaN NaN -1 ADDVALUE %> FOR ABS` outputs the correct new GTS object that is not a clone.

2023-10-06 12:41 UTC, pi-r-p requested changes

2023-10-06 12:41 UTC, pi-r-p commented on warp10/src/main/java/io/warp10/script/functions/NumericalUnaryFunction.java
> +            if (LongUnaryOperator.identity() == opD) { // only case where GTSopD is null and opD is not
you mean DoubleUnaryOperator.identity() for opD ?

2023-10-06 12:41 UTC, pi-r-p commented on warp10/src/main/java/io/warp10/script/functions/NumericalUnaryFunction.java
> +    GTSopD = null == opD || LongUnaryOperator.identity() == opD ? null : new GTSOpsHelper.GTSUnaryOp() {
you mean DoubleUnaryOperator.identity() for opD ?

2023-10-11 11:20 UTC, pi-r-p commented
PTAL

2023-10-11 12:46 UTC, pi-r-p approved these changes

2023-10-11 13:04 UTC, merged