Merge Warp10-ext-Interpolation into WarpLib
senx/warp10-platform pull request #1348
Opened 2024-02-22 09:14 UTC by randomboolean

Merging and adapting interpolation extension

2024-02-28 15:18 UTC, pi-r-p approved these changes

2024-03-26 13:08 UTC, stggn requested changes

2024-03-26 13:08 UTC, stggn commented on warp10/src/main/java/io/warp10/script/interpolation/INTERPOLATOR_3D.java
> +      double y = ((Number) values[1]).doubleValue();
Missing type check

2024-03-26 13:08 UTC, stggn commented on warp10/src/main/java/io/warp10/script/interpolation/INTERPOLATOR_3D.java
> +      xval[i] = ((Number) o1.get(i)).doubleValue();
Missing type check

2024-03-26 13:08 UTC, stggn commented on warp10/src/main/java/io/warp10/script/interpolation/INTERPOLATOR_3D.java
> +      yval[i] = ((Number) o2.get(i)).doubleValue();
Missing type check

2024-03-26 13:08 UTC, stggn commented on warp10/src/main/java/io/warp10/script/interpolation/INTERPOLATOR_3D.java
> +      zval[i] = ((Number) o3.get(i)).doubleValue();
Missing type check

2024-03-26 13:08 UTC, stggn commented on warp10/src/main/java/io/warp10/script/interpolation/INTERPOLATOR_ND.java
> +        point[i] = ((Number) l.get(i)).doubleValue();
Missing type check

2024-03-26 13:08 UTC, stggn commented on warp10/src/main/java/io/warp10/script/interpolation/INTERPOLATOR_ND.java
> +        point[i] = ((Number) values[i]).doubleValue();
Missing type check

2024-03-26 13:08 UTC, stggn commented on warp10/src/main/java/io/warp10/script/interpolation/INTERPOLATOR_ND.java
> +        throw new WarpScriptException(getName() + " expects a List of List as first argument.");
double type should be check here

2024-03-26 16:31 UTC, stggn approved these changes

2024-03-27 13:14 UTC, merged