Optimized metadata handling
senx/warp10-platform pull request #816
Opened 2020-08-21 07:54 UTC by hbs

2020-09-02 08:13 UTC, hbs commented
PTAL

2020-09-03 10:14 UTC, ftence requested changes

2020-09-03 10:14 UTC, ftence commented on warp10/src/main/java/io/warp10/continuum/gts/GTSHelper.java
> +    }
You must add `if (lastchunkid > newestChunk)`.

Also, the same idea as above comment can apply here: drop `zeroChunkCount` and update `chunkcount` with `chunkcount -= (lastchunkid - newestChunk) / chunkwidth`

2020-09-04 08:03 UTC, hbs commented
PTAL

2020-09-04 09:54 UTC, ftence requested changes

2020-09-04 09:54 UTC, ftence commented on warp10/src/main/java/io/warp10/continuum/gts/GTSHelper.java
> +    // or the overlap
Please update the comment to reflect the code below.

2020-09-04 09:54 UTC, ftence commented on warp10/src/main/java/io/warp10/continuum/gts/GTSHelper.java
> +    // If chunkcount is ot 0, adjust the number of chunks
typo "ot" -> "not".

2020-09-04 12:05 UTC, hbs commented
PTYAL

2020-09-04 15:06 UTC, ftence approved these changes

2020-09-05 13:52 UTC, merged