Make POW work on GTSs and Lists the same way numerical functions do
senx/warp10-platform pull request #833
Opened 2020-09-17 15:16 UTC by ftence

2020-09-17 15:25 UTC, hbs requested changes

2020-09-17 15:25 UTC, hbs commented on warp10/src/main/java/io/warp10/script/binary/POW.java
> +      GTSOpsHelper.GTSBinaryOp op = new GTSOpsHelper.GTSBinaryOp() {
This does not depend on the operands, can it be instantiated once and reused?

2020-09-17 15:25 UTC, hbs commented on warp10/src/main/java/io/warp10/script/binary/POW.java
> +      GeoTimeSerie result = op1gts ? ((GeoTimeSerie) op1).cloneEmpty(n) : ((GeoTimeSerie) op2).cloneEmpty();
missing hint if op2 is a GTS

2020-09-17 15:25 UTC, hbs commented on warp10/src/main/java/io/warp10/script/binary/POW.java
> +      GeoTimeSerie.TYPE type = (gts.getType() == GeoTimeSerie.TYPE.LONG && op instanceof Long) ? GeoTimeSerie.TYPE.LONG : GeoTimeSerie.TYPE.DOUBLE;
GeoTimeSerie.TYPE.LONG == gts.getType()

2020-09-18 08:19 UTC, ftence commented
Use a different approach.
Used in conjunction with #832, makes POW work on GTSs.

2020-09-22 12:51 UTC, merged