Metadata ordering
senx/warp10-platform pull request #862
Opened 2020-10-20 15:38 UTC by hbs

Internal modifications so classes are scanned in the order of their classId, thus returning results in lexicographic order of classId+labelsId.

2020-11-03 14:16 UTC, ftence requested changes

2020-11-03 14:16 UTC, ftence commented on warp10/src/main/java/io/warp10/continuum/DirectoryUtil.java
> +                                             Map<String, Map<Long, String>> classesPerOwner,
Update copyright notice.

2020-11-03 14:16 UTC, ftence commented on warp10/src/main/java/io/warp10/standalone/StandaloneDirectoryClient.java
> +
Unused.

2020-11-03 14:16 UTC, ftence commented on warp10/src/main/java/io/warp10/standalone/StandaloneDirectoryClient.java
> +import io.warp10.continuum.gts.MetadataIdComparator;
Unused.

2020-11-03 14:16 UTC, ftence commented on warp10/src/main/java/io/warp10/standalone/StandaloneDirectoryClient.java
> +
Unused.

2020-11-04 12:35 UTC, hbs commented
PTAL

2020-11-04 15:13 UTC, ftence approved these changes

2020-11-04 15:16 UTC, merged