Shamir Secret Sharing Scheme functions
senx/warp10-platform pull request #927
Opened 2021-03-02 13:20 UTC by hbs

2021-03-02 13:29 UTC, trepca commented
oh, wow, how could this be applied? I mean, I assume multiple clients would have to simultaneously come together to execute a secure script?

2021-03-02 14:08 UTC, hbs commented
The use cases are plentiful, the two added functions simply enable the splitting and recovery of data with a K out of N scheme, your creativity will do the rest ;-)

2021-03-02 21:15 UTC, ftence requested changes

2021-03-02 21:57 UTC, hbs commented
PTAL

2021-03-03 08:49 UTC, ftence approved these changes

2021-03-03 08:50 UTC, merged