Crypto.updates
senx/warp10-platform pull request #936
Opened 2021-03-22 08:46 UTC by hbs

2021-03-22 14:30 UTC, ftence requested changes

2021-03-22 14:30 UTC, ftence commented on warp10/src/main/java/io/warp10/script/WarpScriptLib.java
> +  public static final String SHA224 = "SHA224";
That would be perfect with `"SHA224"` preceding `"SHA256"`.

2021-03-22 14:30 UTC, ftence commented on warp10/src/main/java/io/warp10/script/WarpScriptLib.java
> +    addNamedWarpScriptFunction(new DIGEST(GOST, GOST3411Digest.class));
Seems there are also Tiger and Whirlpool digests available. I don't know it there are worth to to be added, though.

2021-03-22 14:30 UTC, ftence commented on warp10/src/main/java/io/warp10/script/WarpScriptLib.java
> +    addNamedWarpScriptFunction(new DIGEST(SHA224, SHA224Digest.class));
Same here, `SHA224` before `SHA256` would make the code much more appealing to the eye ;).

2021-03-22 16:02 UTC, hbs commented
PTAL

2021-03-23 10:20 UTC, ftence approved these changes

2021-03-23 10:42 UTC, merged