Add support for signing macros
senx/warp10-platform pull request #938
Opened 2021-03-23 14:30 UTC by hbs

2021-03-23 21:04 UTC, ftence requested changes

2021-03-23 21:04 UTC, ftence commented on warp10/src/main/java/io/warp10/script/functions/MSIGINFO.java
> +      return false;
Surprisingly, it seems it doesn't break anything but I doubt this `return` is intended.

2021-03-23 21:34 UTC, hbs commented on warp10/src/main/java/io/warp10/script/functions/MVERIFY.java
> +    }
MVERIFY leaves the signature in the macro so we need to copy the statements in a new Macro to be able to snapshot it correctly. MDETACH suppresses the signature from the macro.

2021-03-24 14:23 UTC, ftence approved these changes

2021-03-24 14:57 UTC, merged