Modified scheduling so it uses System.nanoTime
senx/warp10-platform pull request #980
Opened 2021-06-25 09:14 UTC by hbs

2021-06-25 15:33 UTC, ftence commented on warp10/src/main/java/io/warp10/script/ScriptRunner.java
>              }
If I'm not mistaken, this is to align with epoch+N*period. As the origin of nanoTime() is unknown, this is not possible to do that like this.

2021-06-28 15:26 UTC, ftence requested changes
Also, loosely related, in ScriptRunnerConsumerFactory, in case the clocks are out of sync between servers
```
              //
              // Check if running is overdue
              //
              
              long now = System.currentTimeMillis();
              
              if (request.getScheduledAt() + request.getPeriodicity() >= now) {
                continue;
              }
```
may skip a run even if it should not.

2021-06-29 07:02 UTC, ftence approved these changes

2021-06-29 11:28 UTC, merged

2021-06-30 09:42 UTC, pi-r-p commented
Tested successfully on an imx8.